utilisateur_homepage:
    path:     /
    defaults: { _controller: UtilisateurBundle:Default:index }

utilisateurs:
    path:     /utilisateurs
    defaults: { _controller: UtilisateurBundle:Utilisateur:liste }

utilisateursCreate:
    path:     /utilisateurs/create
    defaults: { _controller: UtilisateurBundle:Utilisateur:create }   