user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

seances:
    resource: "@SeancesBundle/Resources/config/routing.yml"
    prefix:   /Seance

materiel:
    resource: "@MaterielBundle/Resources/config/routing.yml"
    prefix:   /Materiel


emploie:
    resource: "@EmploieBundle/Resources/config/routing.yml"
    prefix:   /emploi

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere

niveau:
    resource: "@NiveauBundle/Resources/config/routing.yml"
    prefix:   /niveaux

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salles

utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app_logout:
    path: /logout
    methods: GET
app_login:
    path: /login
    methods: GET