matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /matiere

niveau:
    resource: "@NiveauBundle/Resources/config/routing.yml"
    prefix:   /niveaux

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salles

utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
