materiel:
    resource: "@MaterielBundle/Resources/config/routing.yml"
    prefix:   /Materiel


emploie:
    resource: "@EmploieBundle/Resources/config/routing.yml"
    prefix:   /emploi

niveau:
    resource: "@NiveauBundle/Resources/config/routing.yml"
    prefix:   /niveaux

salle:
    resource: "@SalleBundle/Resources/config/routing.yml"
    prefix:   /salles

utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
