examen_homepage:
    path:     /Examen/list
    defaults: { _controller: ExamenBundle:Examen:liste }

ExamenCreate:
    path:     /Examen/create
    defaults: { _controller: ExamenBundle:Examen:create }

EmploieExamen:
    path:     /Examen/emploie
    defaults: { _controller: ExamenBundle:Examen:emploieExamen }

ExamenDelete:
    path: /delete/{id}
    defaults: { _controller: ExamenBundle:Examen:delete }