absence_homepage:
    path:     /
    defaults: { _controller: AbsenceBundle:Default:index }

absenceCreate:
    path:     /create
    defaults: { _controller: AbsenceBundle:Absence:create }

AbsenceSuivant:
    path:     /suivant/{seance_id}/
    defaults: { _controller: AbsenceBundle:Absence:suivant }